workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      java: 17
      node: 18
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Fix gradlew permissions
        script: |
          chmod +x android/gradlew

      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
          cd ..

      - name: Generate Codegen (RN 0.7x/0.8x fix)
        script: |
          cd android
          ./gradlew :app:generateCodegenArtifactsFromSchema || true
          cd ..

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..

    artifacts:
      - android/app/build/outputs/**/*.apk
