workflows:
  android-apk:
    name: RN CLI Android APK (Stable Final)

    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 18
      java: 17

    cache:
      cache_paths:
        - ~/.npm
        - ~/.gradle

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          java -version

      - name: Clean node + android caches
        script: |
          rm -rf node_modules
          rm -rf android/.gradle
          rm -rf android/app/.cxx
          rm -rf android/build
          rm -rf android/app/build

      - name: Install dependencies
        script: |
          npm install

      # ✅ gradlew permission + line ending safe for mac/linux
      - name: Fix gradlew permissions
        script: |
          chmod +x android/gradlew || true
          sed -i '' 's/\r$//' android/gradlew || true

      # ✅ disable new arch → fixes CMake/codegen JNI missing crash
      - name: Disable new architecture
        script: |
          echo "newArchEnabled=false" >> android/gradle.properties || true

      - name: Gradle clean
        script: |
          cd android
          ./gradlew clean
          cd ..

      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon --stacktrace
          cd ..

      # ✅ print apk path to logs (debug visibility)
      - name: Show built APK files
        script: |
          ls -R android/app/build/outputs/apk || true

    artifacts:
      - android/app/build/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - your_email_here@example.com
