workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 17
      node: 18

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          cd ..
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk

    publishing:
      email:
        recipients:
          - yourmail@gmail.com
