name: Android Build (React Native)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Install dependencies (clean)
        run: |
          rm -rf node_modules
          rm -rf android/.gradle
          rm -rf android/app/.cxx
          rm -rf android/build
          rm -rf android/app/build
          npm cache clean --force
          npm install

      - name: Fix gradlew permissions + CRLF
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix android/gradlew
          chmod +x android/gradlew

      - name: Gradle clean + generate codegen
        run: |
          cd android
          ./gradlew clean
          ./gradlew :app:generateCodegenArtifactsFromSchema
          cd ..

      - name: Build APK Release
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon
          cd ..

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk
